### PR TITLE
Use the streaming api to show response as soon as possible.

### PR DESCRIPTION
**Pull request by NWylynko**
The two main changes I made noticeable to the user:
- Made the chat window bigger
- Streamed the llm response so it starts responding as soon as possible

Some dev changes I have made
- Used [PNPM](https://pnpm.io/) instead of npm for faster dependency install time
  - Including setting it as the package manager in package.json so people don't accidentally use the wrong package manger
- Installed [Shadcn/ui](https://ui.shadcn.com/) for its beautiful components
- Attempted at typing some of the window.ai api to ensure type safe consumption of it through the app
- Moved some of the layout components (header, footer, etc) to the root layout.tsx
- Installed [Zustand](https://docs.pmnd.rs/zustand) and created two zustand stores
  - `useLLMSettingsStore` is responsible for the llm's settings, and gets written to the local storage using the zustand `persist` middleware
  - `useLLMStore` holds the current llm session and the messages sent / generated in the chat
- Installed and used [react-markdown](https://www.npmjs.com/package/react-markdown) to display the llm's response in, as sometimes the llm responds with markdown
- Installed [react-hook-form](https://react-hook-form.com/) and along with [zod](https://zod.dev/) used it to manage forms in the app
- Used next/dynamic lazy function to lazy load components that should only run on the client side (due to them using the window object)

### CODE REVIEW

**Comment by NWylynko** [comment]
By the way, where have you found any documentation of this window.ai api? I can't find anything online about it

**Comment by ksawery29** [comment]
> By the way, where have you found any documentation of this window.ai api? I can't find anything online about it

I don't know if there is any documentation for it yet. I found out about it on twitter https://x.com/mortenjust/status/1805190952358650251?s=46

**Comment by NWylynko** [comment]
> > By the way, where have you found any documentation of this window.ai api? I can't find anything online about it
> 
> I don't know if there is any documentation for it yet. I found out about it on twitter https://x.com/mortenjust/status/1805190952358650251?s=46

Lmao Ofc

**Comment by ksawery29** [comment]
Hey after looking through your pull request I think it would be better to keep it as a fork and not merge it since a lot of stuff changed im not familiar with, thanks anyways

**Pull request closed without merging**
